# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d082d7dd0b93c632a818c2ac90b4f49703adef28a227b18151121572cadba58173c597daf96759d854a6bd065f1555dacb41ae46e6b98d7e9ee257ba24869a8

test:
  secret_key_base: 49544dddb6099f5506bd86027431cc9ee1c30896880d368e65a1bec98d7af2816eb7145288d27c7bdd28b77aeb14aa9a374da3be8f9b4ea32f13df108bead32c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
